#pragma kernel Postprocess

Texture2D<float> Input;
RWStructuredBuffer<float> Output;

[numthreads(1, 1, 1)]
void Postprocess(uint id : SV_DispatchThreadID)
{
    // Softmax function
    float scores[10];
    float sum = 0;

    for (uint i = 0; i < 10; i++)
    {
        scores[i] = exp(Input[uint2(i, 0)]);
        sum += scores[i];
    }

    for (i = 0; i < 10; i++)
        Output[i] = scores[i] / sum;
}
