#pragma kernel Postprocess

StructuredBuffer<float> Input;
RWStructuredBuffer<float> Output;

[numthreads(1, 1, 1)]
void Postprocess(uint id : SV_DispatchThreadID)
{
    // Softmax function
    float temp[10];
    float sum = 0;

    for (uint i = 0; i < 10; i++)
    {
        temp[i] = exp(Input[i]);
        sum += temp[i];
    }

    for (i = 0; i < 10; i++)
        Output[i] = temp[i] / sum;
}
